name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
      
      # Generate the snake
- name: Generate github-contribution-grid-snake.svg
        uses: Platane/svg@v3
        with:
          github_user_name: theparmeshkumar
          outputs: |
           dist/github-contribution-grid-snake.svg?color_snake=%230506A1&color_dots=%23f3f4f6,%23c7d2fe,%238da2fb,%235469d4,%230506A1 
           dist/github-contribution-grid-snake-dark.svg?color_snake=%23FFD900&color_dots=%23161b22,%230506A1,%235469d4,%238da2fb,%23FFD900
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Push the generated files to the output branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
